/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ExampleDiamond,
  ExampleDiamondInterface,
} from "../ExampleDiamond";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "facetAddress",
            type: "address",
          },
          {
            internalType: "enum IDiamondCut.FacetCutAction",
            name: "action",
            type: "uint8",
          },
          {
            internalType: "bytes4[]",
            name: "functionSelectors",
            type: "bytes4[]",
          },
        ],
        indexed: false,
        internalType: "struct IDiamondCut.FacetCut[]",
        name: "_diamondCut",
        type: "tuple[]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_init",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "_calldata",
        type: "bytes",
      },
    ],
    name: "DiamondCut",
    type: "event",
    _diamondFacet: "DiamondCutFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "initializer",
        type: "string",
      },
    ],
    name: "InitLog",
    type: "event",
    _diamondFacet: "ExampleInitFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
    _diamondFacet: "ExampleOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
    _diamondFacet: "ExampleOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
    _diamondFacet: "ExampleOwnershipFacet",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
    _diamondFacet: "ExampleOwnershipFacet",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_initializationContractAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_calldata",
        type: "bytes",
      },
    ],
    name: "InitializationFunctionReverted",
    type: "error",
    _diamondFacet: "DiamondCutFacet",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0xa217fddf",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "facetAddress",
            type: "address",
          },
          {
            internalType: "enum IDiamondCut.FacetCutAction",
            name: "action",
            type: "uint8",
          },
          {
            internalType: "bytes4[]",
            name: "functionSelectors",
            type: "bytes4[]",
          },
        ],
        internalType: "struct IDiamondCut.FacetCut[]",
        name: "_diamondCut",
        type: "tuple[]",
      },
      {
        internalType: "address",
        name: "_init",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_calldata",
        type: "bytes",
      },
    ],
    name: "diamondCut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "DiamondCutFacet",
    _diamondSelector: "0x1f931c1c",
  },
  {
    inputs: [],
    name: "diamondInitialize000",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleInitFacet",
    _diamondSelector: "0xc47ea632",
  },
  {
    inputs: [],
    name: "diamondInitialize100",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleInitFacet",
    _diamondSelector: "0xd4fb2a3e",
  },
  {
    inputs: [],
    name: "diamondInitUpgrade100",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleInitFacet",
    _diamondSelector: "0xfef41fe4",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_functionSelector",
        type: "bytes4",
      },
    ],
    name: "facetAddress",
    outputs: [
      {
        internalType: "address",
        name: "facetAddress_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "DiamondLoupeFacet",
    _diamondSelector: "0xcdffacc6",
  },
  {
    inputs: [],
    name: "facetAddresses",
    outputs: [
      {
        internalType: "address[]",
        name: "facetAddresses_",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "DiamondLoupeFacet",
    _diamondSelector: "0x52ef6b2c",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_facet",
        type: "address",
      },
    ],
    name: "facetFunctionSelectors",
    outputs: [
      {
        internalType: "bytes4[]",
        name: "_facetFunctionSelectors",
        type: "bytes4[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "DiamondLoupeFacet",
    _diamondSelector: "0xadfca15e",
  },
  {
    inputs: [],
    name: "facets",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "facetAddress",
            type: "address",
          },
          {
            internalType: "bytes4[]",
            name: "functionSelectors",
            type: "bytes4[]",
          },
        ],
        internalType: "struct IDiamondLoupe.Facet[]",
        name: "facets_",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "DiamondLoupeFacet",
    _diamondSelector: "0x7a0ed627",
  },
  {
    inputs: [],
    name: "getMonitorData",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
    _diamondFacet: "ExampleUpgradeFacet",
    _diamondSelector: "0xd3ce6863",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "getRoleAdmin",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x248a9ca3",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getRoleMember",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x9010d07c",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "getRoleMemberCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0xca15c873",
  },
  {
    inputs: [],
    name: "getSelector",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
    _diamondFacet: "ExampleUpgradeFacet",
    _diamondSelector: "0x034899bc",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x2f2ff15d",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x91d14854",
  },
  {
    inputs: [],
    name: "isDeployed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
    _diamondFacet: "ExampleUpgradeFacet",
    _diamondSelector: "0xc52046de",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x8da5cb5b",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0x36568abe",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0xd547741f",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "DiamondLoupeFacet",
    _diamondSelector: "0x01ffc9a7",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0xf2fde38b",
  },
  {
    inputs: [],
    name: "UPGRADER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
    _diamondFacet: "ExampleOwnershipFacet",
    _diamondSelector: "0xf72c0d8b",
  },
] as const;

export class ExampleDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): ExampleDiamondInterface {
    return new Interface(_abi) as ExampleDiamondInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ExampleDiamond {
    return new Contract(address, _abi, runner) as unknown as ExampleDiamond;
  }
}
