/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
export type { ExampleDiamond } from "./ExampleDiamond";
export * as factories from "./factories";
export { ExampleDiamond__factory } from "./factories/ExampleDiamond__factory";
