// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title DiamondDeployment
 * @notice Auto-generated deployment data for ExampleDiamond
 * @dev PLACEHOLDER - This file will be auto-generated by: npx hardhat forge:deploy --diamond ExampleDiamond
 * @dev Generated from: diamonds/ExampleDiamond/deployments/examplediamond-hardhat-31337.json
 * DO NOT EDIT MANUALLY - Regenerate using: npx hardhat forge:generate-helpers
 */
library DiamondDeployment {
    // Placeholder Diamond address - will be replaced during deployment
    address constant DIAMOND_ADDRESS = address(0);

    /**
     * @notice Get the Diamond contract address
     * @return The address of the deployed Diamond
     */
    function getDiamondAddress() internal pure returns (address) {
        require(DIAMOND_ADDRESS != address(0), "DiamondDeployment: No deployment found - run forge:deploy first");
        return DIAMOND_ADDRESS;
    }

    /**
     * @notice Get a facet address by name
     * @param facetName The name of the facet
     * @return The address of the facet (returns address(0) if not found)
     */
    function getFacetAddress(string memory facetName) internal pure returns (address) {
        // Placeholder - will be populated during generation
        facetName; // silence unused warning
        return address(0);
    }

    /**
     * @notice Get a function selector
     * @param facetName The name of the facet
     * @param functionName The name of the function
     * @return The function selector (returns bytes4(0) if not found)
     */
    function getSelector(string memory facetName, string memory functionName) internal pure returns (bytes4) {
        // Placeholder - will be populated during generation
        facetName; // silence unused warning
        functionName; // silence unused warning
        return bytes4(0);
    }
}
